### PR TITLE
Properly handle image searches by URL or photo ID

### LINKED ISSUE #19: Searching for photo by ID/URL no longer works
**Problem Description**
As recently as 2d89f034f47d73c9759d4f3831f329da45f78728 inserting a photo by URL or photo ID fails. Unsplash's JSON response is different depending on whether a query parameter is given, and currently this isn't accounted for.

**Proposed Solution**
Determine if the API response is for a search query or photo ID and either:
* Process the data differently, or
* Convert the response into an array so that the existing query processing can handle it.

**System Information**
* Sketch 54.1
* Unsplash Plugin v1.0.7

### PR DESCRIPTION
**Pull request by maxdavid**
Fixes #19
Since https://github.com/BohemianCoding/unsplash-sketchplugin/commit/2d89f034f47d73c9759d4f3831f329da45f78728, searching for a photo by URL or photo ID would fail. By converting the JSON response to an array, the existing code can now properly handle ID searches.

### CODE REVIEW

File: src/unsplash.js [hunk 1]
```diff
@@ -95,6 +95,11 @@ export function getImagesURLsForItems (items, { searchTerm, photoId }) {
           if (json.errors) {
             return Promise.reject(json.errors[0])
           }
+          if (!Array.isArray(json)) {
```
Comment (mathieudutour) [inline src/unsplash.js]: Ah good catch, I missed it.

But I think there is a more efficient fix: instead of doing the whole `Promise.all` thing, we can just skip it completely when there is a photoId. That way we only do 1 API call.
Does that make sense?

Comment (maxdavid) [reply src/unsplash.js]: Good idea! Added a new commit that skips it.

However, DataProvider still fetches the same image multiple times for each frame size. We might want to fix that as well.

Comment (mathieudutour) [reply src/unsplash.js]: That's a good point. Could you open a follow up issue? It doesn't need to be fixed here
